"""
ORM models for the serving / operational store.

These tables are the single source of truth that the API and the AI agent read
from at request time, and that the Airflow pipelines write to in batch.
"""

from datetime import datetime

from sqlalchemy import (
    JSON,
    BigInteger,
    Column,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
)

from db.session import Base


class CustomerFeature(Base):
    """RFM + behavioral features per customer (+ synthesized contact email)."""

    __tablename__ = "customer_features"

    customer_id = Column(BigInteger, primary_key=True)
    email = Column(String(255))

    recency = Column(Float)
    frequency = Column(Float)
    monetary = Column(Float)
    avg_basket_size = Column(Float)
    avg_purchase_interval = Column(Float)
    product_diversity = Column(Float)
    avg_quantity_per_txn = Column(Float)
    return_rate = Column(Float)
    days_as_customer = Column(Float)

    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class ChurnPrediction(Base):
    """Latest churn score per customer."""

    __tablename__ = "churn_predictions"

    customer_id = Column(BigInteger, primary_key=True)
    churn_probability = Column(Float, nullable=False, default=0.5)
    p_alive = Column(Float)
    predicted_clv = Column(Float)
    churn_risk_level = Column(String(16), index=True)
    model_version = Column(String(64))
    scored_at = Column(DateTime, default=datetime.utcnow)


class Segment(Base):
    """Actionable customer segment derived from churn risk + CLV + RFM."""

    __tablename__ = "segments"

    customer_id = Column(BigInteger, primary_key=True)
    segment = Column(String(64), index=True)
    playbook = Column(String(64))
    priority = Column(Integer, default=0)
    rationale = Column(Text)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Recommendation(Base):
    """A recommended product for a customer, produced by a batch run."""

    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(String(64), index=True)
    customer_id = Column(BigInteger, index=True)
    stock_code = Column(String(64))
    description = Column(Text)
    score = Column(Float)
    rank = Column(Integer)
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (Index("ix_recommendations_customer_run", "customer_id", "run_id"),)


class AgentRun(Base):
    """Full trace of a single agent decision for a single customer."""

    __tablename__ = "agent_runs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(String(64), index=True)
    customer_id = Column(BigInteger, index=True)
    segment = Column(String(64))
    churn_probability = Column(Float)
    strategy = Column(Text)
    reasoning = Column(Text)
    tools_used = Column(JSON)
    recommended_items = Column(JSON)
    offer = Column(JSON)
    status = Column(String(32), default="completed")
    created_at = Column(DateTime, default=datetime.utcnow)


class Notification(Base):
    """A notification (email) generated by the agent and its delivery status."""

    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(String(64), index=True)
    customer_id = Column(BigInteger, index=True)
    channel = Column(String(32), default="email")
    to_address = Column(String(255))
    subject = Column(Text)
    body = Column(Text)
    offer = Column(JSON)
    status = Column(String(32), default="pending", index=True)
    error = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    sent_at = Column(DateTime)
